############################################################################
# boards/spike-prime-hub/src/Makefile
############################################################################

include $(TOPDIR)/Make.defs

include Make.defs

include $(TOPDIR)/boards/Board.mk

ARCHSRCDIR = $(TOPDIR)$(DELIM)arch$(DELIM)$(CONFIG_ARCH)$(DELIM)src
BOARDDIR = $(ARCHSRCDIR)$(DELIM)board
CFLAGS += ${INCDIR_PREFIX}$(BOARDDIR)$(DELIM)include
