############################################################################
# apps/Makefile (external apps)
############################################################################

MENUDESC = "External Applications"

include $(APPDIR)/Directory.mk
