using FluentAssertions;
using ImuViewer.Core.Calibration;
using Xunit;

namespace ImuViewer.Core.Tests.Calibration;

public class ImuCalibrationTests
{
    private static string WriteTemp(string body)
    {
        string path = Path.Combine(
            Path.GetTempPath(), $"imu_cal_{Guid.NewGuid():N}.txt");
        File.WriteAllText(path, body);
        return path;
    }

    [Fact]
    public void Load_parses_schema_v1_file()
    {
        string body = """
            # Auto-generated by tools/imu_cal/imu_tk_output_to_cfg.py
            schema_version = 1
            nominal_gyro_radps_per_lsb = 6.108652e-04
            nominal_accel_ms2_per_lsb  = 5.985504e-04
            fsr_gy_dps = 1000
            fsr_xl_g = 2
            odr_hz = 107
            ambient_temp_c = 28.1

            gyro_bias_lsb_x1000  = 22406 65567 11412
            accel_bias_lsb_x1000 = -390870 12782 80597

            gyro_M_x1000  = 997 -1 18 5 988 -3 -1 -10 1002
            accel_M_x1000 = 1008 -2 9 0 1002 3 0 0 1002
            """;
        string path = WriteTemp(body);
        try
        {
            ImuCalibration cal = ImuCalibration.Load(path);
            cal.FsrGyDps.Should().Be(1000);
            cal.FsrXlG.Should().Be(2);
            cal.OdrHz.Should().Be(107);
            cal.AmbientTempC.Should().BeApproximately(28.1f, 1e-3f);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ApplyGyro_subtracts_bias_and_applies_identity_matrix()
    {
        // Identity matrix M = I, bias = (10, 20, 30) LSB.
        string body = """
            schema_version = 1
            fsr_gy_dps = 1000
            fsr_xl_g = 2
            odr_hz = 104
            ambient_temp_c = 25.0
            gyro_bias_lsb_x1000  = 10000 20000 30000
            accel_bias_lsb_x1000 = 0 0 0
            gyro_M_x1000  = 1000 0 0 0 1000 0 0 0 1000
            accel_M_x1000 = 1000 0 0 0 1000 0 0 0 1000
            """;
        string path = WriteTemp(body);
        try
        {
            ImuCalibration cal = ImuCalibration.Load(path);
            System.Numerics.Vector3 g = cal.ApplyGyro(100, 200, 300);
            g.X.Should().BeApproximately(90f, 1e-3f);
            g.Y.Should().BeApproximately(180f, 1e-3f);
            g.Z.Should().BeApproximately(270f, 1e-3f);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ApplyAccel_uses_full_3x3_matrix()
    {
        // Off-diagonal misalignment: M = [[1.0, 0.1, 0],[0,1.0,0],[0,0,1.0]]
        // Bias = 0. So corrected.X = 1.0 * raw.X + 0.1 * raw.Y.
        string body = """
            schema_version = 1
            fsr_gy_dps = 1000
            fsr_xl_g = 2
            odr_hz = 104
            ambient_temp_c = 25.0
            gyro_bias_lsb_x1000  = 0 0 0
            accel_bias_lsb_x1000 = 0 0 0
            gyro_M_x1000  = 1000 0 0 0 1000 0 0 0 1000
            accel_M_x1000 = 1000 100 0 0 1000 0 0 0 1000
            """;
        string path = WriteTemp(body);
        try
        {
            ImuCalibration cal = ImuCalibration.Load(path);
            System.Numerics.Vector3 a = cal.ApplyAccel(100, 200, 0);
            a.X.Should().BeApproximately(100f + 0.1f * 200f, 1e-3f);
            a.Y.Should().BeApproximately(200f, 1e-3f);
            a.Z.Should().BeApproximately(0f, 1e-3f);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void Load_rejects_unsupported_schema()
    {
        string body = """
            schema_version = 99
            fsr_gy_dps = 1000
            fsr_xl_g = 2
            odr_hz = 104
            ambient_temp_c = 25.0
            gyro_bias_lsb_x1000  = 0 0 0
            accel_bias_lsb_x1000 = 0 0 0
            gyro_M_x1000  = 1000 0 0 0 1000 0 0 0 1000
            accel_M_x1000 = 1000 0 0 0 1000 0 0 0 1000
            """;
        string path = WriteTemp(body);
        try
        {
            Action act = () => ImuCalibration.Load(path);
            act.Should().Throw<InvalidDataException>().WithMessage("*schema_version=99*");
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void Load_rejects_missing_key()
    {
        // Drop accel_M_x1000.
        string body = """
            schema_version = 1
            fsr_gy_dps = 1000
            fsr_xl_g = 2
            odr_hz = 104
            ambient_temp_c = 25.0
            gyro_bias_lsb_x1000  = 0 0 0
            accel_bias_lsb_x1000 = 0 0 0
            gyro_M_x1000  = 1000 0 0 0 1000 0 0 0 1000
            """;
        string path = WriteTemp(body);
        try
        {
            Action act = () => ImuCalibration.Load(path);
            act.Should().Throw<InvalidDataException>().WithMessage("*accel_M_x1000*");
        }
        finally
        {
            File.Delete(path);
        }
    }
}
